language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kelseythej/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kelseythej/docker-react npm run test -- --coverage